spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 16379
    password:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/demo?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: guddqs
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9797