# 存放 默认配置
spring:
  redis:
    jedis:
      pool:
        max-active: 100
        max-idle: 5
  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 7MB
      max-request-size: 20MB
server:
  port: 8080
  tomcat:
    max-threads: 20
    max-connections: 200
    accept-count: 50
  servlet:
    context-path: /
mybatis:
  type-aliases-package: cn.gudqs
  mapper-locations: classpath:mybatis-mapper/*/*.xml
logging:
  config: classpath:logback.xml
mapper:
  mappers: cn.gudqs.base.BaseSqlMapper
  identity: MYSQL
  style: normal